refactor: 임시 폰트, 컬러 시스템 적용
working-space/working-space-react-native pull request #1
Opened 2021-12-25 12:33 UTC by leejiwonn

- 폰트, 컬러 시스템 반영 : 추후 디자인 시스템 확정 시 수정 필요합니다.
- 스포카 한 산스 네오 폰트 적용 : Android, iOS 둘 다 반영했습니다. Android는 확인 필요합니다.
- Typo 컴포넌트 생성 : 사용 방법은 Login 참고하시면 됩니다. 기본 제공되는 Text 컴포넌트 대신, 해당 컴포넌트 사용해주세요 😊

2021-12-25 13:19 UTC, Puterism requested changes
리팩토링의 시작! 첫 삽을 축하드립니다 👏👏
Typo 컴포넌트 관련 리뷰와 함께 몇몇 코멘트를 남겨두었으니 확인 부탁드릴게요!

2021-12-25 13:19 UTC, Puterism commented on src/utils/font.ts
> +    return FontSize.SIZE_BODY_02;
모든 `FontType` 별로 조건문을 작성해둬서 타입스크립트에서 `Unreachable code detected`라고 알려줬어요
참고 부탁드릴게요!

2021-12-25 13:19 UTC, Puterism commented on src/utils/font.ts
> +    return Weight.REGULAR;
동일하게 `Unreachable code detected` 입니다

2021-12-25 13:19 UTC, Puterism commented on src/utils/font.ts
> +// eslint-disable-next-line @typescript-eslint/no-namespace
![image](https://user-images.githubusercontent.com/2542730/147385461-e40a856b-9c49-4562-8e52-bd410de6944d.png)
저한테는 이렇게 보이는데 추가하신 이유가 있으신가요?

2021-12-25 13:19 UTC, Puterism commented on src/components/Typo/Typo.styles.tsx
> +  textDecorationLine: string;
함수 컴포넌트로 wrap하지 않고 Styled Component 그대로 export한 뒤, `FontType`을 prop으로 받게 한 뒤, 스타일을 분기 처리해주는 건 어떨까요?
디자인 시스템에 정의할 텍스트만 가져와서 사용할 수 있을 것 같아요

2021-12-25 13:19 UTC, Puterism commented on src/components/Typo/Typo.styles.tsx
> +  textDecorationLine: string;
컴포넌트를 사용할 때, 텍스트에 대한 스타일 정의를 prop에 넣게 되니, 어떤 역할을 하는 컴포넌트인지 코드만 보았을 때 파악하기 어렵다는 문제가 있을 것 같아요
추가로, 만약에 prop에 미처 정의하지 못한 스타일을 주어야 할 때, Typo 컴포넌트의 prop 정의를 수정해야 하는 번거로움도 있을 것 같아요

2021-12-25 13:19 UTC, Puterism commented on src/components/Typo/Typo.tsx
> +interface Props {
`TextProps`를 extends해서 정의해주면, `Text` 컴포넌트에서 사용할 수 있는 prop 정의를 모두 가져올 수 있어요

2021-12-25 13:19 UTC, Puterism commented on src/utils/color.ts
> +} as const;
적절한 팔레트 정의 좋아요 👍

2021-12-25 13:19 UTC, Puterism commented on src/utils/font.ts
> +namespace Font {
namespace는 처음 봤어요 😮 공부하러 갑니다

2021-12-25 14:52 UTC, leejiwonn commented on src/utils/font.ts
> +// eslint-disable-next-line @typescript-eslint/no-namespace
네임스페이스 사용을 금지하는 강화된 룰을 적용했을 때 작성했던 주석입니다. 현재는 필요하지 않으니 바로 삭제하겠습니다!

2021-12-25 14:57 UTC, leejiwonn commented on src/utils/font.ts
> +    return FontSize.SIZE_BODY_02;
저 부분으로 넘어갈 케이스가 없어보이니 제거하겠습니다!

2021-12-25 16:13 UTC, leejiwonn commented on src/components/Typo/Typo.styles.tsx
> +  textDecorationLine: string;
props 를 하나하나 모두 지정해놓는 방식은 제한적이라는 의견에 동의합니다. 이 부분은 styles 를 props 로 받아오는 방식을 사용해 해결하겠습니다.

2021-12-26 09:01 UTC, Puterism requested changes
리뷰 반영 감사합니다 👍 
한 가지 코멘트에 대해서 의견 전달이 잘 안 된 것 같아요 ㅠㅠ
좀 더 풀어서 코멘트를 작성해두었으니 확인 부탁드릴게요!

2021-12-26 09:01 UTC, Puterism commented on src/utils/types.ts
> +export type ExtendComponentProps<T extends JSXElementConstructor<any>, P> = Omit<ComponentProps<T>, keyof P> & P;
어떤 역할을 하는 유틸 타입인지 간단하게 설명해주실 수 있나요?

2021-12-26 09:01 UTC, Puterism commented on src/components/Typo/Typo.tsx
> +}: Props) => {
앞서 드렸던 코멘트를 좀 더 풀어서 말씀드릴게요!

```ts
import { TextProps } from 'react-native';
```
리액트 네이티브에는 이렇게 `<Text>`에서 사용할 수 있는 props에 대한 타입 정의를 `TextProps`에 해두었어요
이를 이용하면 `Typo` 컴포넌트에서 `<Text>`의 prop들을 그대로 사용할 수 있게 타입을 정의할 수 있어요

```tsx
interface Props extends TextProps {
  font?: FontType;
  color?: GrayColor | PrimaryColor | SecondColor | SubColor;
  align?: Align;
}
```
`children`이나 `onPress`같은 경우는 `TextProps`에 이미 정의되어 있으니, 새롭게 정의해주어야 하는 prop들만 별도로 추가해주면 됩니다.

`TextProps`를 그대로 활용하면, Typo 컴포넌트의 활용성도 그만큼 높아질 수 있고, 필요한 prop을 그때그때 다시 정의해주어야 하는 번거로움도 없앨 수 있을 거라고 생각해요. 이렇게 타입을 정의해보는 건 어떤지 제안 드려요!

2021-12-26 09:01 UTC, Puterism commented on src/components/Typo/Typo.tsx
> +}: Props) => {
더 나아가서, 아래와 같이 parameter에 `...props`와 같이 가져와서 바로 `<Text>`에 넣어줄 수 있어요
```tsx
const Typo = ({
  font = FontType.REGULAR_BODY_02,
  color = GrayColor.GRAY_400,
  align = Align.LEFT,
  ...props, // 요렇게
}: Props) => {
  const fontStyle = Font.getStyle(font);

  return (
    <TypoStyled
      family={Font.getFamily(fontStyle.weight)}
      size={fontStyle.size}
      weight={fontStyle.weight}
      color={color}
      align={align}
      {...props} // 그리고 요렇게요
    />
  );
}
```

2021-12-27 11:46 UTC, leejiwonn commented on src/components/Typo/Typo.tsx
> +}: Props) => {
오 `TextProps` 를 제공하고 있군요. 이해했습니다! 이 방법으로 교체하겠습니다.

2021-12-27 11:48 UTC, leejiwonn commented on src/utils/types.ts
> +export type ExtendComponentProps<T extends JSXElementConstructor<any>, P> = Omit<ComponentProps<T>, keyof P> & P;
`JSXElementConstructor` 로 확장한 특정 컴포넌트(T)의 속성을 바탕으로, 두 번째로 입력받은 P로 덮어쓴다는 의미입니다. 말 그대로 컴포넌트를 확장하는 유틸 타입입니다! `TextProps` 라고 따로 제공하는 줄 몰라서 사용한 부분이니 제거하겠습니다 😂

2021-12-27 12:03 UTC, Puterism approved these changes
수고하셨습니다! 👍

2021-12-27 12:04 UTC, merged