refactor: Detail 스크린 UI 구현 및 관련 컴포넌트/데이터 재정의
working-space/working-space-react-native pull request #4
Opened 2022-01-09 08:00 UTC by leejiwonn

2022-01-09 12:37 UTC, Puterism requested changes
리팩토링 수고하셨어요!
몇 가지 질문과 피드백을 남겨놓았으니 확인 부탁드릴게요!

2022-01-09 12:37 UTC, Puterism commented on src/components/Loading/Loading.tsx
> +  color?: GrayColor | PrimaryColor | SecondColor | SubColor;
이런 색상 팔레트는 자주 사용하게 될 것 같은데 나중에 `Color`라는 타입으로 따로 정의해서 재사용할 수 있겠네요

2022-01-09 12:37 UTC, Puterism commented on src/components/NoneImage/NoneImage.styles.tsx
> +  width: 91%;
이 width는 왜 91%인가요?

2022-01-09 12:37 UTC, Puterism commented on src/components/SetTags/SetTags.tsx
> +            style={css`
`SetTags.styles`에서 별도로 정의하고 import해서 사용해주세요!

2022-01-09 12:37 UTC, Puterism commented on src/components/SetTags/SetTags.styles.tsx
> +  width: 96.6%;
위와 마찬가지로 96.6%인 이유가 있나요?

2022-01-09 12:37 UTC, Puterism commented on src/models/tag.ts
> +export type TagSet = Record<TagName, TagItem>;
좋은 아이디어였어요 👍

2022-01-09 12:37 UTC, Puterism commented on src/screens/Detail/Detail.tsx
> +        title: cafeData?.name,
`cafeData?.name`이 `undefined`가 되면 카페 이름도 `undefined`가 되겠네요 🤔
`??` 연산자 같은 걸로 예외처리가 필요해보여요!

2022-01-09 12:37 UTC, Puterism commented on src/screens/Detail/Detail.tsx
> +    console.log(text);
추후 리팩토링하기에 조금 번거로울 수 있을 것 같아서 불필요한 `console.log`를 걷어낼 필요가 있을 것 같아요
나중에 ESLint no-console 규칙을 추가해야 겠네요...

지금은 지우지 않으셔도 괜찮지만 앞으로 작업해주실 때 불필요한 `console.log`가 있다면 삭제해주세요!

2022-01-09 12:37 UTC, Puterism commented on src/screens/Detail/Detail.tsx
> +  if (cafeData === undefined) {
`cafeData`가 `null`과 같은 falsy한 값이 오는 경우가 있나요?
만약에 그렇지 않다면 `!cafeData`와 같이 수정해주어도 좋을 것 같아요

2022-01-09 12:37 UTC, Puterism commented on src/screens/Detail/Detail.tsx
> +            <Header.Button onPress={() => goBack()}>
혹시 화살표 함수에 wrapping하지 않고 그냥 `goBack`을 넣으면 에러가 발생하나요?

2022-01-09 12:37 UTC, Puterism commented on src/screens/Detail/Detail.tsx
> +        onBackdropPress={() => handleCloseButton()}
`handleCloseButton`만 넣어도 동작할 것 같아요

2022-01-09 12:37 UTC, Puterism commented on src/screens/Main/Main.tsx
> +                address: address,
```suggestion
                address,
```

2022-01-09 12:37 UTC, Puterism commented on src/screens/Main/Main.tsx
> +                address: address,
중요한 건 아니지만 불편해서...😠  ㅋㅋㅋㅋㅋ

2022-01-09 12:37 UTC, Puterism commented on src/screens/Main/Main.tsx
>                  id: id,
요것도!

2022-01-10 13:39 UTC, leejiwonn commented on src/components/Loading/Loading.tsx
> +  color?: GrayColor | PrimaryColor | SecondColor | SubColor;
컬러 시스템이 확정될 때 한 번 수정해보겠습니다!

2022-01-11 08:35 UTC, leejiwonn commented on src/components/SetTags/SetTags.tsx
> +            style={css`
헉 이 부분을 못봤네요. 수정하겠습니다!

2022-01-11 08:44 UTC, leejiwonn commented on src/screens/Detail/Detail.tsx
> +    console.log(text);
현재 테스트를 위해 남겨둔 콘솔이니 상세 페이지 기능 확인 후 바로 삭제하겠습니다! 추후 규칙을 추가하는 방향도 좋은 것 같습니다. 😊

2022-01-11 08:48 UTC, leejiwonn commented on src/screens/Detail/Detail.tsx
> +            <Header.Button onPress={() => goBack()}>
정상 동작합니다. wrapping 제거하도록 하겠습니다.

2022-01-11 08:53 UTC, leejiwonn commented on src/screens/Main/Main.tsx
> +                address: address,
ㅎㅎ 이 부분은 변경된 데이터 형태로 일괄적용하면서 바꾸겠습니다. 😉

2022-01-11 08:55 UTC, leejiwonn commented on src/screens/Detail/Detail.tsx
> +        title: cafeData?.name,
카페 이름이 없을 경우 빈 문자열로 표시되도록 변경하겠습니다!

2022-01-11 08:56 UTC, leejiwonn commented on src/screens/Detail/Detail.tsx
> +  if (cafeData === undefined) {
`cafeData` 자체가 `null`로 들어오는 경우는 없을 것 같습니다. 데이터를 받기 전 `undefined` 또는 정규화 된 데이터가 들어오게 되어있으니 말씀해주신대로 수정하겠습니다. 😄

2022-01-11 09:21 UTC, leejiwonn commented on src/components/NoneImage/NoneImage.styles.tsx
> +  width: 91%;
부모 기준 100% 채웠을 때, 기본 마진값이 양옆 4.5% 들어가도록 하기 위해 91%로 주었습니다. 아예 100%로 하고 부모 쪽에서 컨트롤하도록 변경해도 괜찮을 것 같네요. 😊

2022-01-11 09:21 UTC, leejiwonn commented on src/components/SetTags/SetTags.styles.tsx
> +  width: 96.6%;
이 또한 위와 마찬가지의 이유입니다!

2022-01-11 11:33 UTC, leejiwonn commented on src/components/NoneImage/NoneImage.styles.tsx
> +  width: 91%;
`width: 100%` 유지하며, 필요한 여백은 패딩으로 반영했습니다.

2022-01-12 13:48 UTC, Puterism approved these changes
리뷰 반영 감사드려요~~
수고 많으셨어요!! 👏👏👏

2022-01-12 14:04 UTC, merged